name: PreRelease Build

on:
  push:
    branches: [ main ]
    paths-ignore:
    - 'doc/**'
    - 'readme.md'
    - 'README.md'

jobs:
  build:

    runs-on: windows-2016

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Nuke Build
      run: ./build.ps1 Push
      env: 
        NugetApiUrl: "https://f.feedz.io/doob/dev/nuget/index.json"
        NugetApiKey: ${{ secrets.FEEDZAPIKEY }}
