name: Release Build

on:
  release:
    types: [published]
    paths-ignore:
    - 'doc/**'
    - 'readme.md'
    - 'README.md'

jobs:
  build:

    runs-on: windows-2016

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Nuke Build
      run: ./build.ps1 Push
      env: 
        NugetApiUrl: "https://api.nuget.org/v3/index.json"
        NugetApiKey: ${{ secrets.NUGETAPIKEY }}
